"""mensagem

Revision ID: 05f15fd9852d
Revises: f0d5cc033cf1
Create Date: 2026-01-08 14:44:55.922149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '05f15fd9852d'
down_revision = 'f0d5cc033cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('estoque_movimentacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('origem', sa.String(length=50), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('saldo_anterior', sa.Integer(), nullable=False),
    sa.Column('saldo_atual', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vidracaria_orders')
    op.drop_table('customers')
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('criado_por', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quantidade_alerta', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('produtos_cd_ean_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('produtos_cd_sku_key'), type_='unique')
        batch_op.create_unique_constraint('uq_produto_empresa_sku', ['empresa_id', 'cd_sku'])
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['criado_por'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ativo')
        batch_op.drop_column('role')
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_produto_empresa_sku', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('produtos_cd_sku_key'), ['cd_sku'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('produtos_cd_ean_key'), ['cd_ean'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('quantidade_alerta')
        batch_op.drop_column('criado_por')
        batch_op.drop_column('empresa_id')

    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('customers_pkey'))
    )
    op.create_table('vidracaria_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('vidracaria_orders_pkey'))
    )
    op.drop_table('estoque_movimentacoes')
    op.drop_table('empresas')
    # ### end Alembic commands ###
