"""add google fields to user

Revision ID: 4a1c720f045a
Revises: fcd5a41c8eeb
Create Date: 2026-01-16 19:20:28.272338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a1c720f045a'
down_revision = 'fcd5a41c8eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('last_login')
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
