"""Criar tabela produtos

Revision ID: e601e8d99fdc
Revises: 
Create Date: 2026-01-05 22:09:04.478171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e601e8d99fdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cd_sku', sa.String(length=50), nullable=False),
    sa.Column('cd_ean', sa.String(length=13), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('vl_compra', sa.Float(), nullable=False),
    sa.Column('porcent_lucro', sa.Float(), nullable=False),
    sa.Column('vl_venda', sa.Float(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('largura_cm', sa.Float(), nullable=True),
    sa.Column('altura_cm', sa.Float(), nullable=True),
    sa.Column('profundidade_cm', sa.Float(), nullable=True),
    sa.Column('foto_url', sa.String(length=300), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cd_ean'),
    sa.UniqueConstraint('cd_sku')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vidracaria_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vidracaria_orders')
    op.drop_table('users')
    op.drop_table('produtos')
    op.drop_table('customers')
    # ### end Alembic commands ###
