"""create produtos

Revision ID: f0d5cc033cf1
Revises: e601e8d99fdc
Create Date: 2026-01-07 20:56:04.730207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d5cc033cf1'
down_revision = 'e601e8d99fdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade_minima', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('quantidade_minima')

    # ### end Alembic commands ###
